metrics:
  enabled: true
  port: 9090
  path: /metrics

prometheus:
  scrape_interval: 15s
  evaluation_interval: 15s

grafana:
  enabled: true
  port: 3000
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://localhost:9090

alerts:
  - name: HighTrainingLoss
    condition: kenga_training_loss > 2.0
    duration: 5m
    severity: warning 